### ISSUE TITLE
as_str() is private

### ISSUE THREAD

**Issue by sowbug** [synek317/synonym#1]
If my newtype is public in my crate, then I might also want `as_str()` to be public. But it seems that https://github.com/synek317/synonym/blob/master/src/impls/string.rs#L25 generates a private method. I worked around it by delegating to a public `as_string()` method (`#[synonym(skip(as_str))]` raised other problems), but that's not ideal.

I imagine I'm the first to encounter this because traits are always public, and `as_str()` isn't a trait but rather a semi-standardized regular method.

Thank you for this crate; except for this issue, it has delivered as promised.

**Comment by synek317** [comment]
Hello, thanks for this good catch. It turned out that the test for that was unlucky - it could see the `as_str` method because the string synonym was defined in the same scope as the test method.

I made it public and released 0.1.2 version.

**Comment by sowbug** [comment]
Wow, that's fast turnaround! I've updated my app, removed the workaround, and confirmed it's working. Thank you very much.
