### ISSUE TITLE
Support NonZero integers

### ISSUE THREAD

**Issue by umut-sahin** [synek317/synonym#3]
Lovely crate :heart_hands: 

I really want to use it in my project but I'm using the new type pattern with [NonZero](https://doc.rust-lang.org/std/num/struct.NonZero.html) types. Would it be possible to add support for them as well?

Thanks!

**Comment by synek317** [comment]
Thank you for the suggestion and kind words. I think it should be a no-brainer, hopefully I will add it soon™.

**Comment by umut-sahin** [comment]
Thanks, looking forward to it :raised_hands:

**Comment by synek317** [comment]
Hello, I've implemented NonZeros here: https://github.com/synek317/synonym/commit/546e70228c8fb8cfc8dc8adc87ba5e6df15feec8

I also realized NonZeros are not implementing math traits (Add/Sub etc.) so synonyms also don't implement them.

I will release the next version soon, probably after implementing the `.value()` method you also suggested.

Thanks for your ideas.

**Comment by umut-sahin** [comment]
Thanks, looking forward to try it!
