### ISSUE TITLE
Provide `.value()` method for `Synonym` types

### ISSUE THREAD

**Issue by umut-sahin** [synek317/synonym#6]
I'm aware that `Deref` is implemented and I can just use `*max_health` or make the field pub and use `max_health.0`, but I find `max_health.value()` to be more readable in some cases, so it'd be nice to have.

**Comment by synek317** [comment]
Closed in https://github.com/synek317/synonym/commit/fb872ffe2d6aac8cad9e25ae7c6f72fdf6e2ad5f. Thanks for reporting this idea!
