### ISSUE TITLE
Why aren't Deref and DerefMut implemented automatically anymore?

### ISSUE THREAD

**Issue by umut-sahin** [synek317/synonym#9]
I find them really useful in some situations and they are essential for the new type pattern. What's the rationale behind this change?

**Comment by synek317** [comment]
They have never been: https://github.com/synek317/synonym/blob/master/src/impls/deref.rs

Implementing Deref and DerefMut for non-smart-pointers is considered an anti-pattern, see for example [here](https://doc.rust-lang.org/book/ch15-02-deref.html) or [here](https://rust-unofficial.github.io/patterns/anti_patterns/deref.html).

Also look at this example:

```
use core::ops::{Deref, DerefMut};

struct Foo(String);

struct Bar(String);
         
impl Deref for Foo {
    type Target = String;
    
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DerefMut for Foo {
    fn deref_mut(&mut self) -> &mut Self::Target { &mut self.0 }
    
}
         
impl Deref for Bar {
    type Target = String;
    
    fn deref(&self) -> &Self::Target { &self.0 }
} 

fn main() {
    let mut foo = Foo("foo".to_string());
    let bar = Bar("bar".to_string());
    
    foo.push_str(&bar);
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b95c4e407813bda08f12c4e5067a9a63))
